version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python main.py
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: python tests.py
  e2e_tests:
    docker:
      - image: mcr.microsoft.com/playwright/python:v1.24.0-focal
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install pytest-playwright
      - run:
          name: Run Playwright tests
          command: pytest path/to/your/e2e/tests
  deploy:
    docker:
      - image: cimg/python:3.11
    steps:
      - run: echo "Deploying to production server"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - e2e_tests:
          requires:
            - test
      - deploy:
          requires:
            - e2e_tests
          filters:
            branches:
              only: main
